import os

AUTH0_DOMAIN = os.getenv("AUTH0_DOMAIN")
AUTH0_API_IDENTIFIER = os.getenv("AUTH0_API_IDENTIFIER")
AUTH0_ALGORITHMS = ["RS256"]

S3_BUCKET_NAME = os.getenv("S3_BUCKET_NAME")

SQS_URL = os.getenv("SQS_URL")

JOB_NODE_AMI_ID = os.getenv("JOB_NODE_AMI_ID")

MONGO_CONN_STRING = os.getenv("MONGO_CONN_STRING")
MONGO_DB_NAME = os.getenv("MONGO_DB_NAME")

PUSHER_APP_ID = os.getenv("PUSHER_APP_ID")
PUSHER_KEY = os.getenv("PUSHER_KEY")
PUSHER_SECRET = os.getenv("PUSHER_SECRET")
PUSHER_CLUSTER = os.getenv("PUSHER_CLUSTER")